//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelonRuntime.ProjectGenerator {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MelonRuntime.ProjectGenerator.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HELLO_WORLD=Hello World.
        /// </summary>
        internal static string DefaultDotEnv {
            get {
                return ResourceManager.GetString("DefaultDotEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a const { process } = Melon.std;
        ///
        ///console.log(process.env.HELLO_WORLD);.
        /// </summary>
        internal static string DefaultEntryPoint {
            get {
                return ResourceManager.GetString("DefaultEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a # Logs
        ///logs
        ///*.log
        ///npm-debug.log*
        ///yarn-debug.log*
        ///yarn-error.log*
        ///lerna-debug.log*
        ///.pnpm-debug.log*
        ///
        ///# Diagnostic reports (https://nodejs.org/api/report.html)
        ///report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
        ///
        ///# Runtime data
        ///pids
        ///*.pid
        ///*.seed
        ///*.pid.lock
        ///
        ///# Directory for instrumented libs generated by jscoverage/JSCover
        ///lib-cov
        ///
        ///# Coverage directory used by tools like istanbul
        ///coverage
        ///*.lcov
        ///
        ///# nyc test coverage
        ///.nyc_output
        ///
        ///# Grunt intermediate storage (https://gruntjs.com/creating-plugins [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string DefaultGitignore {
            get {
                return ResourceManager.GetString("DefaultGitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a module.exports = {
        ///  mode: &quot;production&quot;
        ///}.
        /// </summary>
        internal static string DefaultWebpackConfig {
            get {
                return ResourceManager.GetString("DefaultWebpackConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;presets&quot;: [&quot;@babel/preset-env&quot;]
        ///}.
        /// </summary>
        internal static string JavaScriptBabelrc {
            get {
                return ResourceManager.GetString("JavaScriptBabelrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;scripts&quot;: {
        ///        &quot;_webpack_from_babel&quot;: &quot;webpack ./babel/main.js --config ./webpack.config.js&quot;,
        ///        &quot;_babel_from_source&quot;: &quot;babel --extensions .js,.ts ./src/ --out-dir ./babel&quot;,
        ///        &quot;dev&quot;: &quot;npx melon load ./src/main.js&quot;,
        ///        &quot;build&quot;: &quot;npm run _babel_from_source  &amp;&amp; npm run _webpack_from_babel&quot;,
        ///        &quot;go&quot;: &quot;npx melon load ./dist/main.js&quot;
        ///    },
        ///    &quot;devDependencies&quot;: {
        ///        &quot;@babel/cli&quot;: &quot;latest&quot;,
        ///        &quot;@babel/core&quot;: &quot;latest&quot;,
        ///        &quot;@babel/preset-env&quot;: &quot;latest&quot;,
        ///  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string JavaScriptPackageJson {
            get {
                return ResourceManager.GetString("JavaScriptPackageJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;presets&quot;: [&quot;@babel/preset-typescript&quot;, &quot;@babel/preset-env&quot;]
        ///}.
        /// </summary>
        internal static string TypeScriptBabelrc {
            get {
                return ResourceManager.GetString("TypeScriptBabelrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;compilerOptions&quot;: {
        ///      &quot;outDir&quot;: &quot;build&quot;,
        ///      &quot;types&quot;: [
        ///        &quot;melon-types&quot;
        ///      ],
        ///      &quot;lib&quot;: [ &quot;es2022&quot; ]
        ///    }
        ///}.
        /// </summary>
        internal static string TypeScriptConfig {
            get {
                return ResourceManager.GetString("TypeScriptConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;scripts&quot;: {
        ///        &quot;_webpack_from_babel&quot;: &quot;webpack ./babel/main.js --config ./webpack.config.js&quot;,
        ///        &quot;_babel_from_source&quot;: &quot;babel --extensions .js,.ts ./src/ --out-dir ./babel&quot;,
        ///        &quot;dev&quot;: &quot;npx melon load ./src/main.js&quot;,
        ///        &quot;build&quot;: &quot;npm run _babel_from_source  &amp;&amp; npm run _webpack_from_babel&quot;,
        ///        &quot;go&quot;: &quot;npx melon load ./dist/main.js&quot;
        ///    },
        ///    &quot;devDependencies&quot;: {
        ///        &quot;@babel/cli&quot;: &quot;latest&quot;,
        ///        &quot;@babel/core&quot;: &quot;latest&quot;,
        ///        &quot;@babel/preset-env&quot;: &quot;latest&quot;,
        ///  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string TypeScriptPackageJson {
            get {
                return ResourceManager.GetString("TypeScriptPackageJson", resourceCulture);
            }
        }
    }
}
