import { _copyFile } from "./_copyFile";
import { _copyFileAsync } from "./_copyFileAsync";
import { _createDirectory } from "./_createDirectory";
import { _createDirectoryAsync } from "./_createDirectoryAsync";
import { _deleteDirectory } from "./_deleteDirectory";
import { _deleteDirectoryAsync } from "./_deleteDirectoryAsync";
import { _deleteFile } from "./_deleteFile";
import { _deleteFileAsync } from "./_deleteFileAsync";
import { _moveFile } from "./_moveFile";
import { _moveFileAsync } from "./_moveFileAsync";
import { _readBytes } from "./_readBytes";
import { _readBytesAsync } from "./_readBytesAsync";
import { _readText } from "./_readText";
import { _readTextAsync } from "./_readTextAsync";
import { _renameFile } from "./_renameFile";
import { _renameFileAsync } from "./_renameFileAsync";
import { _writeBytes } from "./_writeBytes";
import { _writeBytesAsync } from "./_writeBytesAsync";
import { _writeText } from "./_writeText";
import { _writeTextAsync } from "./_writeTextAsync";
declare const _fs: {
    readText: typeof _readText;
    writeText: typeof _writeText;
    readBytes: typeof _readBytes;
    writeBytes: typeof _writeBytes;
    readTextAsync: typeof _readTextAsync;
    writeTextAsync: typeof _writeTextAsync;
    readBytesAsync: typeof _readBytesAsync;
    writeBytesAsync: typeof _writeBytesAsync;
    deleteFile: typeof _deleteFile;
    deleteFileAsync: typeof _deleteFileAsync;
    moveFile: typeof _moveFile;
    moveFileAsync: typeof _moveFileAsync;
    copyFile: typeof _copyFile;
    renameFile: typeof _renameFile;
    renameFileAsync: typeof _renameFileAsync;
    copyFileAsync: typeof _copyFileAsync;
    createDirectory: typeof _createDirectory;
    createDirectoryAsync: typeof _createDirectoryAsync;
    deleteDirectory: typeof _deleteDirectory;
    deleteDirectoryAsync: typeof _deleteDirectoryAsync;
};
export { _fs };
