//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelonJS.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MelonJS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;presets&quot;: [&quot;@babel/preset-typescript&quot;, &quot;@babel/preset-env&quot;]
        ///}.
        /// </summary>
        internal static string NewProjectBabelrc {
            get {
                return ResourceManager.GetString("NewProjectBabelrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a console.log(&quot;Hello world!&quot;).
        /// </summary>
        internal static string NewProjectEntryPoint {
            get {
                return ResourceManager.GetString("NewProjectEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a # Logs
        ///logs
        ///*.log
        ///npm-debug.log*
        ///yarn-debug.log*
        ///yarn-error.log*
        ///lerna-debug.log*
        ///.pnpm-debug.log*
        ///
        ///# Diagnostic reports (https://nodejs.org/api/report.html)
        ///report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
        ///
        ///# Runtime data
        ///pids
        ///*.pid
        ///*.seed
        ///*.pid.lock
        ///
        ///# Directory for instrumented libs generated by jscoverage/JSCover
        ///lib-cov
        ///
        ///# Coverage directory used by tools like istanbul
        ///coverage
        ///*.lcov
        ///
        ///# nyc test coverage
        ///.nyc_output
        ///
        ///# Grunt intermediate storage (https://gruntjs.com/creating-plugins [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string NewProjectGitIgnore {
            get {
                return ResourceManager.GetString("NewProjectGitIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;name&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;version&quot;: &quot;1.0.0&quot;,
        ///    &quot;website&quot;: &quot;&quot;,
        ///    &quot;entryPoint&quot;: &quot;dist/main.js&quot;
        ///}.
        /// </summary>
        internal static string NewProjectMelonInfo {
            get {
                return ResourceManager.GetString("NewProjectMelonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;scripts&quot;: {
        ///    &quot;go&quot;: &quot;babel --extensions .ts ./src/ --out-dir ./babel &amp;&amp; webpack ./babel/index.js &amp;&amp; npx melon load .&quot;
        ///  },
        ///  &quot;dependencies&quot;: {
        ///  },
        ///  &quot;devDependencies&quot;: {
        ///    &quot;@babel/cli&quot;: &quot;latest&quot;,
        ///    &quot;@babel/core&quot;: &quot;latest&quot;,
        ///    &quot;@babel/preset-env&quot;: &quot;latest&quot;,
        ///    &quot;@babel/preset-typescript&quot;: &quot;latest&quot;,
        ///    &quot;melon-types&quot;: &quot;latest&quot;,
        ///    &quot;webpack-cli&quot;: &quot;latest&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string NewProjectPackageInfo {
            get {
                return ResourceManager.GetString("NewProjectPackageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ## 🍈 MelonJS Project
        ///
        ///| Command | Description |
        ///| ------- | ----------- |
        ///| `npm i melon-runtime -g` | Installs MelonJS (requires .NET 6 SDK and Runtime) |
        ///| `npm install` | Installs the required MelonJS types |
        ///| `npm run go` | Run the project |.
        /// </summary>
        internal static string NewProjectReadme {
            get {
                return ResourceManager.GetString("NewProjectReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;compilerOptions&quot;: {
        ///      &quot;outDir&quot;: &quot;build&quot;,
        ///      &quot;types&quot;: [
        ///        &quot;melon-types&quot;
        ///      ],
        ///      &quot;lib&quot;: [ &quot;es2015&quot;, &quot;DOM&quot; ]
        ///    }
        ///}.
        /// </summary>
        internal static string NewProjectTsconfig {
            get {
                return ResourceManager.GetString("NewProjectTsconfig", resourceCulture);
            }
        }
    }
}
